name: nn_model_deployment
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  tflite_flutter: ^0.9.0
  image: ^3.1.0
  image_picker: ^0.8.4+4
  image_cropper: ^1.4.1
  path_provider: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/xor.tflite
    - assets/selfie2anime.tflite
